fs=require('fs')
// fs.mkdirSync("Hello")
fs.writeFileSync("Hello/user.txt","CRUD")
fs.appendFileSync("Hello/user.txt","\noperation")
var data=fs.readFileSync("Hello/user.txt","utf-8")
console.log(data)
fs.renameSync("Hello/user.txt","Hello/user1.txt")
fs.unlinkSync("Hello/user1.txt")
fs.rmdirSync("Hello")
