# Generated by Django 4.2.4 on 2025-07-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_name', models.CharField(max_length=20)),
                ('review', models.IntegerField()),
                ('download', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='game_images/')),
            ],
        ),
    ]
