# Generated by Django 4.2.5 on 2025-07-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddGame1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type_name', models.CharField(max_length=40)),
                ('review', models.IntegerField()),
                ('download', models.IntegerField()),
            ],
        ),
    ]
