# Generated by Django 4.2.4 on 2025-07-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0004_delete_addgame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('marks', models.IntegerField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='AddGame1',
        ),
    ]
