# Generated by Django 4.2.5 on 2025-07-10 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0003_addgame1_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddGame',
        ),
    ]
